CREATE TABLE point_of_interest (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    category VARCHAR(50),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


GRANT ALL PRIVILEGES ON DATABASE mds TO mariarebecca;--//change mds with your db name, mariarebecca with your username
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mariarebecca;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mariarebecca;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO mariarebecca;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO mariarebecca;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO mariarebecca;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO mariarebecca;